<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
						font-size: 14px;
						color: #333;
						margin: 0;
						background-color: #f7f9fc;
					}
					.container {
						max-width: 1000px;
						margin: 40px auto;
						padding: 40px;
						background: #fff;
						box-shadow: 0 4px 12px rgba(0,0,0,0.05);
						border-radius: 12px;
					}
					h1 {
						font-weight: 800;
						font-size: 24px;
						margin: 0 0 10px 0;
						color: #111;
					}
					p {
						color: #666;
						margin: 0 0 30px 0;
					}
					table {
						width: 100%;
						border-collapse: collapse;
					}
					th {
						text-align: left;
						padding: 12px 15px;
						border-bottom: 2px solid #eee;
						font-weight: 700;
						text-transform: uppercase;
						font-size: 11px;
						letter-spacing: 0.1em;
						color: #999;
					}
					td {
						padding: 12px 15px;
						border-bottom: 1px solid #f0f0f0;
                        word-break: break-all;
					}
					tr:hover td {
						background-color: #fcfcfc;
					}
					a {
						color: #2563eb;
						text-decoration: none;
						font-weight: 500;
					}
					a:hover {
						text-decoration: underline;
					}
					.priority-high { color: #059669; font-weight: bold; }
					.footer {
						margin-top: 30px;
						font-size: 12px;
						color: #aaa;
						text-align: center;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<h1>XML Sitemap</h1>
					<p>Generated by Lizardware CMS. This index contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
					<table>
						<thead>
							<tr>
								<th width="70%">URL</th>
								<th width="10%">Priority</th>
								<th width="20%">Last Modified</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="sitemap:urlset/sitemap:url">
								<tr>
									<td>
										<xsl:variable name="itemURL">
											<xsl:value-of select="sitemap:loc"/>
										</xsl:variable>
										<a href="{$itemURL}">
											<xsl:value-of select="sitemap:loc"/>
										</a>
									</td>
									<td>
										<xsl:choose>
											<xsl:when test="sitemap:priority &gt; 0.7">
												<span class="priority-high">
													<xsl:value-of select="concat(sitemap:priority*100, '%')"/>
												</span>
											</xsl:when>
											<xsl:otherwise>
												<span>
													<xsl:value-of select="concat(sitemap:priority*100, '%')"/>
												</span>
											</xsl:otherwise>
										</xsl:choose>
									</td>
									<td>
										<xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), ' ', substring(sitemap:lastmod, 12, 5))"/>
									</td>
								</tr>
							</xsl:for-each>
						</tbody>
					</table>
					<div class="footer">
						Lizardware CMS • Edge Native • Global Sync
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
